
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author veloso
 */
public class Empresa extends javax.swing.JFrame {

    /**
     * Creates new form Empresa
     */
    public Empresa() {
        initComponents();
        jTFVendas.setVisible(false);
        jCBNivel.setVisible(false);
        jLRetornaFuncao.setVisible(false);
        jLRetornaComissaoGratificacao.setVisible(false);
        jLRetornaSalario.setVisible(false);
        jLRetornaMatricula.setVisible(false);
    }
    
    Vendedor vendedor;
    Gerente gerente;
    Funcionario funcionario;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLVendasNivel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCBFuncionario = new javax.swing.JCheckBox();
        jCBVendedor = new javax.swing.JCheckBox();
        jCBGerente = new javax.swing.JCheckBox();
        jLFuncao = new javax.swing.JLabel();
        jLComissaoGratificacao = new javax.swing.JLabel();
        jTFNome = new javax.swing.JTextField();
        jTFMatricula = new javax.swing.JTextField();
        jTFSalario = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFVendas = new javax.swing.JTextField();
        jCBNivel = new javax.swing.JComboBox<>();
        jBCalcular = new javax.swing.JButton();
        jLRetornaFuncao = new javax.swing.JLabel();
        jLRetornaComissaoGratificacao = new javax.swing.JLabel();
        jLRetornaSalario = new javax.swing.JLabel();
        jLMatricula = new javax.swing.JLabel();
        jLRetornaMatricula = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EMPRESA");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("CADASTRAR FUNCIONARIO");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setText("MATRICULA");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setText("SALARIO R$");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setText("NOME");

        jLVendasNivel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLVendasNivel.setText("  ");
        jLVendasNivel.setEnabled(false);

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel7.setText("TIPO:");

        jCBFuncionario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jCBFuncionario.setText("FUNCIONARIO");
        jCBFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBFuncionarioActionPerformed(evt);
            }
        });

        jCBVendedor.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jCBVendedor.setText("VENDEDOR");
        jCBVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBVendedorActionPerformed(evt);
            }
        });

        jCBGerente.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jCBGerente.setText("GERENTE");
        jCBGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGerenteActionPerformed(evt);
            }
        });

        jLFuncao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLFuncao.setText("FUNÇÃO");

        jLComissaoGratificacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLComissaoGratificacao.setText("COMISSÃO");

        jTFNome.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNomeActionPerformed(evt);
            }
        });

        jTFMatricula.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jTFSalario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel6.setText("SALARIO LIQUIDO");

        jTFVendas.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jTFVendas.setEnabled(false);

        jCBNivel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jCBNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nível 1", "Nível 2", "Nível 3", "Nível 4", "Nível 5" }));
        jCBNivel.setEnabled(false);

        jBCalcular.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jBCalcular.setText("CALCULAR");
        jBCalcular.setEnabled(false);
        jBCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCalcularActionPerformed(evt);
            }
        });

        jLRetornaFuncao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLRetornaFuncao.setText("jLabel8");

        jLRetornaComissaoGratificacao.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLRetornaComissaoGratificacao.setText("jLabel8");

        jLRetornaSalario.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLRetornaSalario.setText("jLabel8");

        jLMatricula.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLMatricula.setText("MATRICULA");

        jLRetornaMatricula.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLRetornaMatricula.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(85, 85, 85)
                                .addComponent(jTFNome))
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFSalario)
                            .addComponent(jTFMatricula))
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLVendasNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTFVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLRetornaSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLComissaoGratificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jLRetornaComissaoGratificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBFuncionario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBVendedor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCBGerente, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBCalcular)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLFuncao)
                                    .addComponent(jLMatricula))
                                .addGap(98, 98, 98)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLRetornaFuncao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLRetornaMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTFMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBFuncionario)
                    .addComponent(jCBVendedor)
                    .addComponent(jCBGerente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLVendasNivel)
                    .addComponent(jTFVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jBCalcular)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLFuncao)
                    .addComponent(jLRetornaFuncao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMatricula)
                    .addComponent(jLRetornaMatricula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLComissaoGratificacao)
                    .addComponent(jLRetornaComissaoGratificacao))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLRetornaSalario))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBFuncionarioActionPerformed
        // TODO add your handling code here:
        if(!jCBFuncionario.isSelected()){
            jCBFuncionario.setSelected(true);
        }
        if(jCBFuncionario.isSelected()){
            jCBVendedor.setSelected(false);
            jCBGerente.setSelected(false);
            jLVendasNivel.setText(" ");
            jLVendasNivel.setEnabled(false);
            jLComissaoGratificacao.setText(" ");
            jTFVendas.setEnabled(false);
            jCBNivel.setEnabled(false);
            jTFVendas.setVisible(false);
            jCBNivel.setVisible(false);
            jBCalcular.setEnabled(true);
        }
    }//GEN-LAST:event_jCBFuncionarioActionPerformed

    private void jCBVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBVendedorActionPerformed
        // TODO add your handling code here:
        if(!jCBVendedor.isSelected()){
            jCBVendedor.setSelected(true);
        }
        if(jCBVendedor.isSelected()){
            jCBFuncionario.setSelected(false);
            jCBGerente.setSelected(false);
            jLVendasNivel.setText("VENDAS R$");
            jLVendasNivel.setEnabled(true);
            jLComissaoGratificacao.setText("COMISSÃO");
            jTFVendas.setEnabled(true);
            jCBNivel.setEnabled(false);
            jTFVendas.setVisible(true);
            jCBNivel.setVisible(false);
            jBCalcular.setEnabled(true);
        }
    }//GEN-LAST:event_jCBVendedorActionPerformed

    private void jCBGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGerenteActionPerformed
        // TODO add your handling code here:
        if(!jCBGerente.isSelected()){
            jCBGerente.setSelected(true);
        }
        if(jCBGerente.isSelected()){
            jCBVendedor.setSelected(false);
            jCBFuncionario.setSelected(false);
            jLVendasNivel.setText("NIVEL");
            jLVendasNivel.setEnabled(true);
            jLComissaoGratificacao.setText("GRATIFICAÇÃO");
            jTFVendas.setEnabled(false);
            jCBNivel.setEnabled(true);
            jTFVendas.setVisible(false);
            jCBNivel.setVisible(true);
            jBCalcular.setEnabled(true);
        }
    }//GEN-LAST:event_jCBGerenteActionPerformed

    private void jTFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFNomeActionPerformed

    private void jBCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCalcularActionPerformed
        // TODO add your handling code here:
        String nome = jTFNome.getText();
        int matricula;
        Double salario;
        int nivel;
        Double vendas;
        try{
            matricula = Integer.parseInt(jTFMatricula.getText());
            salario = Double.valueOf(jTFSalario.getText());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Informe a matrícula e o salário.");
            matricula = 0;
            salario = 0.0;
        }
        String funcao;
        if(jCBFuncionario.isSelected()){
            funcao = "FUNCIONARIO";
            funcionario = new Funcionario(matricula, salario, nome, funcao);
            jLRetornaFuncao.setText(funcionario.getFuncao() + " " + funcionario.getNome());
            jLRetornaSalario.setText("R$ "+ String.format("%.2f", funcionario.getSalario()));
            jLRetornaSalario.setVisible(true);
            jLRetornaFuncao.setVisible(true);
            jLRetornaComissaoGratificacao.setVisible(false);
            jLRetornaMatricula.setText(String.valueOf(funcionario.getMatricula()));
            jLRetornaMatricula.setVisible(true);
        }
        if(jCBGerente.isSelected()){
            funcao = "GERENTE";
            nivel = jCBNivel.getSelectedIndex()+1;
            gerente = new Gerente(nivel, matricula, salario, nome, funcao);
            jLRetornaFuncao.setText(gerente.getFuncao() + " " + gerente.getNome());
            jLRetornaSalario.setText("R$ "+ String.format("%.2f", gerente.getSalario()));
            jLRetornaComissaoGratificacao.setText("R$ "+ String.format("%.2f", gerente.calculaGratificacao()));
            jLRetornaSalario.setVisible(true);
            jLRetornaFuncao.setVisible(true);
            jLRetornaComissaoGratificacao.setVisible(true);
            jLRetornaMatricula.setText(String.valueOf(gerente.getMatricula()));
            jLRetornaMatricula.setVisible(true);
        }
        if(jCBVendedor.isSelected()){
            funcao = "VENDEDOR";
            try{
             vendas = Double.valueOf(jTFVendas.getText());
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Informe o total de vendas.");
                vendas = 0.0;
            }
            vendedor = new Vendedor(vendas, matricula, salario, nome, funcao);
            jLRetornaFuncao.setText(vendedor.getFuncao() + " " + vendedor.getNome());
            jLRetornaSalario.setText("R$ "+ String.format("%.2f", vendedor.getSalario()));
            jLRetornaComissaoGratificacao.setText("R$ "+ String.format("%.2f", vendedor.calculaComissao()));
            jLRetornaSalario.setVisible(true);
            jLRetornaFuncao.setVisible(true);
            jLRetornaComissaoGratificacao.setVisible(true);
            jLRetornaMatricula.setText(String.valueOf(vendedor.getMatricula()));
            jLRetornaMatricula.setVisible(true);
        }
    }//GEN-LAST:event_jBCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Empresa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Empresa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCalcular;
    private javax.swing.JCheckBox jCBFuncionario;
    private javax.swing.JCheckBox jCBGerente;
    private javax.swing.JComboBox<String> jCBNivel;
    private javax.swing.JCheckBox jCBVendedor;
    private javax.swing.JLabel jLComissaoGratificacao;
    private javax.swing.JLabel jLFuncao;
    private javax.swing.JLabel jLMatricula;
    private javax.swing.JLabel jLRetornaComissaoGratificacao;
    private javax.swing.JLabel jLRetornaFuncao;
    private javax.swing.JLabel jLRetornaMatricula;
    private javax.swing.JLabel jLRetornaSalario;
    private javax.swing.JLabel jLVendasNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTFMatricula;
    private javax.swing.JTextField jTFNome;
    private javax.swing.JTextField jTFSalario;
    private javax.swing.JTextField jTFVendas;
    // End of variables declaration//GEN-END:variables
}
